version: '3'
services:
  api:
    image: lyrnox/fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    environment:
      - DATABASE_HOST=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_EXPIRE=${ACCESS_EXPIRE}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
